@host = http://localhost:3000
@accessToken = PEGAR_ACCESS_TOKEN
@refreshToken = PEGAR_REFRESH_TOKEN


### register
POST {{host}}/api/user/register
Content-Type: application/json

{
  "email": "alumno@bildy.test",
  "password": "Password123"
}


### validar email (codigo sale en consola)
PUT {{host}}/api/user/validation
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "code": "123456"
}


### login
POST {{host}}/api/user/login
Content-Type: application/json

{
  "email": "alumno@bildy.test",
  "password": "Password123"
}


### onboarding
PUT {{host}}/api/user/register
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Ana",
  "lastName": "Garcia Lopez",
  "nif": "12345678Z"
}


### company - business
PATCH {{host}}/api/user/company
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "type": "business",
  "name": "Bildy SL",
  "cif": "B12345678",
  "street": "Calle Falsa",
  "number": 123,
  "postal": "28080",
  "city": "Madrid",
  "province": "Madrid"
}


### company - freelance
PATCH {{host}}/api/user/company
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "type": "freelance",
  "street": "Calle Sol",
  "number": 1,
  "postal": "28001",
  "city": "Madrid",
  "province": "Madrid"
}


### logo (cambiar la ruta del archivo)
PATCH {{host}}/api/user/logo
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./logo.png
------boundary--


### get me
GET {{host}}/api/user
Authorization: Bearer {{accessToken}}


### refresh
POST {{host}}/api/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### logout
POST {{host}}/api/user/logout
Authorization: Bearer {{accessToken}}


### delete soft
DELETE {{host}}/api/user?soft=true
Authorization: Bearer {{accessToken}}


### delete hard
DELETE {{host}}/api/user?soft=false
Authorization: Bearer {{accessToken}}


### invite (solo admin)
POST {{host}}/api/user/invite
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "compi@bildy.test"
}


### change password
PATCH {{host}}/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "Password123",
  "newPassword": "NuevaPass456",
  "confirmPassword": "NuevaPass456"
}


### health
GET {{host}}/api/health
